name: ymlpipeline
trigger: none
pool: default
steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    backendServiceArm: 'pkserviceconection'
    backendAzureRmResourceGroupName: 'bipin-rg'
    backendAzureRmStorageAccountName: 'bkumar765'
    backendAzureRmContainerName: 'tfstatecontainer'
    backendAzureRmKey: 'pks.terraform.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/dev'